login_login_homepage:
    path:     /index
    defaults: { _controller: LoginLoginBundle:Default:index }
    
login_login_login:
    path:     /login
    defaults: { _controller: LoginLoginBundle:Default:login }
